_wandb:
    value:
        cli_version: 0.27.0
        e:
            ekcpbh421el6us2c7mpt8km6kf16arak:
                codePath: learning-cbf/train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 20
                disk:
                    /:
                        total: "308494532608"
                        used: "245366345728"
                email: balinbb@stud.ntnu.no
                executable: /home/bb/Desktop/eth-v26/ATIC_ABB_Learning_CBF/.venv/bin/python3
                git:
                    commit: 78b488a441c804c1bd93cbce9d7019346c0a6952
                    remote: git@github.com:Axel-ZZ/ATIC_ABB_Learning_CBF.git
                host: bb-Yoga-Pro-7-14ASP10
                memory:
                    total: "32893771776"
                os: Linux-6.17.0-22-generic-x86_64-with-glibc2.39
                program: /home/bb/Desktop/eth-v26/ATIC_ABB_Learning_CBF/learning-cbf/train.py
                python: CPython 3.13.12
                root: /home/bb/Desktop/eth-v26/ATIC_ABB_Learning_CBF/learning-cbf
                startedAt: "2026-05-14T16:41:43.973892Z"
                writerId: ekcpbh421el6us2c7mpt8km6kf16arak
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 13
                - 16
            "4": 3.13.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
batch_size:
    value: 512
dataset:
    value: set_01
epochs:
    value: 200
hidden:
    value: 64
in_dim:
    value: 5
lr:
    value: 0.001
margin:
    value: 0.1
