"""
Kinodynamic RRT for a differential-drive robot, with optional CasADi
trajectory smoothing.

Designed to plug straight into your DiffDriveKinematics: every tree edge
is generated by forward-integrating the same RK4 discrete dynamics, so
the resulting path is dynamically feasible (subject to (v, omega) limits).

Usage
-----
    from diff_drive_kinematics import RobotModel, DiffDriveKinematics
    from rrt_diff_drive import RRTPlanner, CircleObstacle, smooth_path

    robot = RobotModel(wheel_radius=0.05, wheel_base=0.3)
    kin   = DiffDriveKinematics(robot)

    obstacles = [CircleObstacle(2.0, 2.0, 0.5)]
    planner = RRTPlanner(
        kin,
        bounds=((-1, -1), (5, 5)),
        obstacles=obstacles,
        v_bounds=(-0.2, 0.5),
        omega_bounds=(-1.5, 1.5),
    )

    start = np.array([0.0, 0.0, 0.0])
    goal  = np.array([4.0, 4.0, 0.0])
    states, controls = planner.plan(start, goal)

    states_s, controls_s = smooth_path(kin, states, controls, obstacles)
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, List, Optional, Sequence, Tuple

import casadi as ca
import numpy as np


# ── Obstacles ───────────────────────────────────────────────────────────
@dataclass
class CircleObstacle:
    """Axis-aligned circular obstacle in the (x, y) plane."""
    x: float
    y: float
    radius: float

    def collides(self, pt: np.ndarray, robot_radius: float = 0.0) -> bool:
        dx = pt[0] - self.x
        dy = pt[1] - self.y
        return dx * dx + dy * dy <= (self.radius + robot_radius) ** 2


# ── Tree bookkeeping ────────────────────────────────────────────────────
@dataclass
class _Node:
    state: np.ndarray            # shape (3,) — x, y, theta
    parent: Optional[int]        # index into RRTPlanner._nodes
    control: Optional[np.ndarray]  # control that produced `state` from parent
    n_steps: int = 1             # how many dt-sized integration steps the edge took


# ── Planner ─────────────────────────────────────────────────────────────
class RRTPlanner:
    """
    Kinodynamic RRT for a unicycle / differential-drive model.

    Each extension samples a random control, holds it for a few dt steps,
    and integrates with the kinematics' RK4 discrete dynamics. The node
    that lands closest to the random target (in SE(2) distance) is added
    to the tree.

    Parameters
    ----------
    kinematics : DiffDriveKinematics
        Provides discrete_dynamics(dt) — must expose .n_states, .n_controls.
    bounds : ((xmin, ymin), (xmax, ymax))
        Sampling bounds for x, y. theta is sampled uniformly in [-pi, pi].
    obstacles : list of CircleObstacle
        Circular obstacles to avoid.
    robot_radius : float
        Inflation radius added to each obstacle for collision checking.
    v_bounds, omega_bounds : (low, high)
        Control limits.
    dt : float
        Integration step size.
    steps_per_extend : int
        How many dt-sized steps a single tree extension applies the control for.
        Larger = faster exploration but coarser paths.
    n_control_samples : int
        How many random controls to try per extension; the best one is kept.
    goal_bias : float
        Probability of sampling the goal instead of a random point.
    goal_tol : (pos_tol, theta_tol)
        Position and heading tolerance for accepting the goal.
    max_iters : int
        Iteration cap.
    seed : int | None
    """

    def __init__(
        self,
        kinematics,
        bounds: Tuple[Tuple[float, float], Tuple[float, float]],
        obstacles: Sequence[CircleObstacle] = (),
        robot_radius: float = 0.0,
        v_bounds: Tuple[float, float] = (-0.3, 0.5),
        omega_bounds: Tuple[float, float] = (-1.5, 1.5),
        dt: float = 0.1,
        steps_per_extend: int = 5,
        n_control_samples: int = 10,
        goal_bias: float = 0.1,
        goal_tol: Tuple[float, float] = (0.15, 0.4),
        max_iters: int = 5000,
        seed: Optional[int] = None,
    ):
        self.kin = kinematics
        self.bounds = (np.asarray(bounds[0], dtype=float),
                       np.asarray(bounds[1], dtype=float))
        self.obstacles = list(obstacles)
        self.robot_radius = float(robot_radius)
        self.v_bounds = v_bounds
        self.omega_bounds = omega_bounds
        self.dt = float(dt)
        self.steps_per_extend = int(steps_per_extend)
        self.n_control_samples = int(n_control_samples)
        self.goal_bias = float(goal_bias)
        self.pos_tol, self.theta_tol = goal_tol
        self.max_iters = int(max_iters)
        self.rng = np.random.default_rng(seed)

        # Pre-build the discrete dynamics once. CasADi Functions are cheap
        # to call but expensive to construct; doing this inside the loop
        # would dominate runtime.
        self._f_disc = self.kin.discrete_dynamics(self.dt, method="rk4")

        self._nodes: List[_Node] = []

    # ── public API ──────────────────────────────────────────────────────
    def plan(
        self,
        start: np.ndarray,
        goal: np.ndarray,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Returns (states, controls).
            states.shape   = (N, 3)
            controls.shape = (N-1, 2)
        Raises RuntimeError if no path is found within max_iters.
        """
        start = np.asarray(start, dtype=float).reshape(3)
        goal = np.asarray(goal, dtype=float).reshape(3)

        if self._point_in_collision(start[:2]):
            raise ValueError("Start state is in collision.")
        if self._point_in_collision(goal[:2]):
            raise ValueError("Goal state is in collision.")

        self._nodes = [_Node(state=start, parent=None, control=None, n_steps=0)]

        for _ in range(self.max_iters):
            target = self._sample(goal)
            nearest_idx = self._nearest(target)
            new_state, control, ok = self._steer(
                self._nodes[nearest_idx].state, target
            )
            if not ok:
                continue

            new_idx = len(self._nodes)
            self._nodes.append(_Node(
                state=new_state,
                parent=nearest_idx,
                control=control,
                n_steps=self.steps_per_extend,
            ))

            if self._reached_goal(new_state, goal):
                return self._reconstruct(new_idx)

        raise RuntimeError(
            f"RRT failed to reach goal within {self.max_iters} iterations."
        )

    # ── internals ───────────────────────────────────────────────────────
    def _sample(self, goal: np.ndarray) -> np.ndarray:
        if self.rng.random() < self.goal_bias:
            return goal.copy()
        lo, hi = self.bounds
        xy = self.rng.uniform(lo, hi)
        th = self.rng.uniform(-np.pi, np.pi)
        return np.array([xy[0], xy[1], th])

    def _nearest(self, target: np.ndarray) -> int:
        states = np.array([n.state for n in self._nodes])
        return int(np.argmin(_se2_distance(states, target)))

    def _steer(
        self,
        from_state: np.ndarray,
        to_state: np.ndarray,
    ) -> Tuple[np.ndarray, np.ndarray, bool]:
        """
        Try `n_control_samples` random controls held for `steps_per_extend`
        steps; return the one whose endpoint is closest to `to_state` and
        whose trajectory is collision-free.
        """
        v_lo, v_hi = self.v_bounds
        w_lo, w_hi = self.omega_bounds

        best_state = None
        best_control = None
        best_dist = np.inf

        for _ in range(self.n_control_samples):
            v = self.rng.uniform(v_lo, v_hi)
            w = self.rng.uniform(w_lo, w_hi)
            u = np.array([v, w])

            traj_ok = True
            s = from_state.copy()
            for _ in range(self.steps_per_extend):
                s = np.asarray(
                    self._f_disc(s, u, self.dt)
                ).flatten()
                if self._point_in_collision(s[:2]):
                    traj_ok = False
                    break
            if not traj_ok:
                continue

            d = float(_se2_distance(s[None, :], to_state)[0])
            if d < best_dist:
                best_dist = d
                best_state = s
                best_control = u

        if best_state is None:
            return from_state, np.zeros(2), False
        return best_state, best_control, True

    def _reached_goal(self, state: np.ndarray, goal: np.ndarray) -> bool:
        pos_err = np.linalg.norm(state[:2] - goal[:2])
        th_err = abs(_wrap(state[2] - goal[2]))
        return pos_err <= self.pos_tol and th_err <= self.theta_tol

    def _point_in_collision(self, pt: np.ndarray) -> bool:
        for o in self.obstacles:
            if o.collides(pt, self.robot_radius):
                return True
        return False

    def _reconstruct(self, end_idx: int) -> Tuple[np.ndarray, np.ndarray]:
        states = []
        controls = []
        idx = end_idx
        while idx is not None:
            node = self._nodes[idx]
            states.append(node.state)
            if node.control is not None:
                # The control was held for `n_steps` integration steps, so
                # replay it to recover the intermediate states for smoother
                # downstream optimization.
                for _ in range(node.n_steps):
                    controls.append(node.control)
            idx = node.parent
        states.reverse()
        controls.reverse()

        # Re-integrate to get the dense state trajectory aligned with the
        # dense controls. (The tree only stored endpoints of each edge.)
        dense_states = [states[0]]
        s = states[0].copy()
        for u in controls:
            s = np.asarray(self._f_disc(s, u, self.dt)).flatten()
            dense_states.append(s)

        return np.array(dense_states), np.array(controls)


# ── Distance helpers ────────────────────────────────────────────────────
def _wrap(a):
    """Wrap angle(s) to [-pi, pi]."""
    return (a + np.pi) % (2 * np.pi) - np.pi


def _se2_distance(
    states: np.ndarray,        # (N, 3)
    target: np.ndarray,        # (3,)
    w_theta: float = 0.3,
) -> np.ndarray:
    """Weighted SE(2) distance with proper angle wrapping."""
    dxy = states[:, :2] - target[:2]
    dth = _wrap(states[:, 2] - target[2])
    return np.sqrt((dxy * dxy).sum(axis=1) + (w_theta * dth) ** 2)


# ── CasADi smoothing ────────────────────────────────────────────────────
def smooth_path(
    kinematics,
    states_init: np.ndarray,        # (N, 3)
    controls_init: np.ndarray,      # (N-1, 2)
    obstacles: Sequence[CircleObstacle] = (),
    robot_radius: float = 0.0,
    dt: float = 0.1,
    v_bounds: Tuple[float, float] = (-0.3, 0.5),
    omega_bounds: Tuple[float, float] = (-1.5, 1.5),
    w_effort: float = 1.0,
    w_smooth: float = 5.0,
    obs_margin: float = 0.05,
    print_level: int = 0,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Polish an RRT path with a single CasADi NLP.

    Fixes the start and goal, keeps the horizon length the same, enforces
    discrete dynamics + control bounds + obstacle clearance, and minimizes
    control effort plus a smoothness term on Δu.

    The RRT output is used as the initial guess, which is what makes this
    converge reliably — solving the same NLP cold is much harder.
    """
    f_disc = kinematics.discrete_dynamics(dt, method="rk4")
    N = controls_init.shape[0]   # number of control intervals

    opti = ca.Opti()
    X = opti.variable(3, N + 1)
    U = opti.variable(2, N)

    # Dynamics
    for k in range(N):
        opti.subject_to(X[:, k + 1] == f_disc(X[:, k], U[:, k], dt))

    # Boundary conditions
    opti.subject_to(X[:, 0]  == states_init[0])
    opti.subject_to(X[:, -1] == states_init[-1])

    # Control bounds
    v_lo, v_hi = v_bounds
    w_lo, w_hi = omega_bounds
    opti.subject_to(opti.bounded(v_lo, U[0, :], v_hi))
    opti.subject_to(opti.bounded(w_lo, U[1, :], w_hi))

    # Obstacle clearance — signed-distance constraints on every state.
    # These are differentiable, which is the whole reason for putting this
    # in CasADi rather than rejection-sampling.
    for o in obstacles:
        r = o.radius + robot_radius + obs_margin
        for k in range(N + 1):
            dx = X[0, k] - o.x
            dy = X[1, k] - o.y
            opti.subject_to(dx * dx + dy * dy >= r * r)

    # Cost
    effort = ca.sumsqr(U)
    dU = U[:, 1:] - U[:, :-1]
    smooth = ca.sumsqr(dU)
    opti.minimize(w_effort * effort + w_smooth * smooth)

    # Warm start from RRT
    opti.set_initial(X, states_init.T)
    opti.set_initial(U, controls_init.T)

    opti.solver("ipopt", {"print_time": False},
                {"print_level": print_level, "sb": "yes"})

    sol = opti.solve()
    return np.array(sol.value(X)).T, np.array(sol.value(U)).T


# ── Demo ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    from enviroments.vehicle_dynamics import RobotModel, DiffDriveKinematics

    robot = RobotModel(wheel_radius=0.05, wheel_base=0.3)
    kin = DiffDriveKinematics(robot)

    obstacles = [
        CircleObstacle(1.5, 1.5, 0.4),
        CircleObstacle(3.0, 2.5, 0.5),
        CircleObstacle(2.0, 3.5, 0.3),
    ]

    planner = RRTPlanner(
        kin,
        bounds=((-0.5, -0.5), (5.0, 5.0)),
        obstacles=obstacles,
        robot_radius=0.1,
        v_bounds=(-0.2, 0.5),
        omega_bounds=(-2.0, 2.0),
        dt=0.1,
        steps_per_extend=5,
        n_control_samples=15,
        goal_bias=0.15,
        goal_tol=(0.2, np.pi),  # heading-free goal; smoother will set final heading
        max_iters=3000,
        seed=0,
    )

    start = np.array([0.0, 0.0, 0.0])
    goal  = np.array([4.0, 4.0, np.pi / 2])

    states, controls = planner.plan(start, goal)
    print(f"RRT path: {len(states)} states, {len(controls)} controls")

    states_s, controls_s = smooth_path(
        kin, states, controls, obstacles,
        robot_radius=0.1, dt=0.1,
        v_bounds=(-0.2, 0.5), omega_bounds=(-2.0, 2.0),
    )
    print(f"Smoothed path: {len(states_s)} states")

    # Plot
    try:
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(7, 7))
        for o in obstacles:
            ax.add_patch(plt.Circle((o.x, o.y), o.radius,
                                    color="tab:red", alpha=0.4))
        ax.plot(states[:, 0], states[:, 1], "-",  color="tab:gray",
                label="RRT raw",  linewidth=1.2)
        ax.plot(states_s[:, 0], states_s[:, 1], "-", color="tab:blue",
                label="CasADi smoothed", linewidth=2)
        ax.plot(*start[:2], "go", markersize=10, label="start")
        ax.plot(*goal[:2],  "r*", markersize=14, label="goal")
        ax.set_aspect("equal")
        ax.legend()
        ax.set_title("Kinodynamic RRT + CasADi smoothing")
        ax.grid(alpha=0.3)
        plt.tight_layout()
        plt.savefig("/home/bb/Desktop/atic-cbfs/plots/rrt.png", dpi=110)
        print("Saved plots")
    except Exception as e:
        print(f"(plot skipped: {e})")